packages:
  - 'packages/*'
allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  better-sqlite3: true
  electron: true
  esbuild: true
  protobufjs: true
  puppeteer: false
  vue-demi: true
